language: php

php:
    - 5.5
    - 5.6

# test only master (+ Pull requests)
branches:
    only:
        - master

before_install:
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
    - composer selfupdate
    - composer install --prefer-dist

script: phpunit --coverage-text

notifications:
    email: false
