language: php

php:
    - 5.4
    - 5.5
    - 5.6

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - composer selfupdate
    - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
    email: false
