parameters:
    # Form types
    ezrepoforms.policy.edit.form.class: EzSystems\RepositoryForms\Form\Type\Role\PolicyType
    ezrepoforms.policy.limitation.form.class: EzSystems\RepositoryForms\Form\Type\Role\LimitationType

    # Validators
    ezrepoforms.validator.unique_role_identifier.class: EzSystems\RepositoryForms\Validator\Constraints\UniqueRoleIdentifierValidator

    # Action dispatchers
    ezrepoforms.action_dispatcher.role.class: EzSystems\RepositoryForms\Form\ActionDispatcher\RoleDispatcher
    ezrepoforms.action_dispatcher.policy.class: EzSystems\RepositoryForms\Form\ActionDispatcher\PolicyDispatcher

    # Form processors
    ezrepoforms.form_processor.role.class: EzSystems\RepositoryForms\Form\Processor\RoleFormProcessor
    ezrepoforms.form_processor.policy.class: EzSystems\RepositoryForms\Form\Processor\PolicyFormProcessor

    ezrepoforms.limitation_form_mapper.registry.class: EzSystems\RepositoryForms\Limitation\LimitationFormMapperRegistry
    ezrepoforms.limitation.form_mapper.siteaccess.class: EzSystems\RepositoryForms\Limitation\SiteAccessLimitationMapper

services:
    # Form types
    ezrepoforms.policy.edit.form:
        class: %ezrepoforms.policy.edit.form.class%
        arguments: [%ezpublish.api.role.policy_map%, @translator, @ezpublish.api.service.role]
        tags:
            - { name: form.type, alias: ezrepoforms_policy_edit }

    ezrepoforms.policy.limitation.form:
        class: %ezrepoforms.policy.limitation.form.class%
        arguments: [@ezrepoforms.limitation_form_mapper.registry]
        tags:
            - { name: form.type, alias: ezrepoforms_policy_limitation_edit }

    # Validators
    ezrepoforms.validator.unique_role_identifier:
        class: %ezrepoforms.validator.unique_role_identifier.class%
        arguments: [@ezpublish.api.service.role]
        tags:
            - { name: validator.constraint_validator, alias: ezrepoforms.validator.unique_role_identifier }

    # Action dispatchers
    ezrepoforms.action_dispatcher.role:
        class: %ezrepoforms.action_dispatcher.role.class%
        parent: ezrepoforms.action_dispatcher.base

    ezrepoforms.action_dispatcher.policy:
        class: %ezrepoforms.action_dispatcher.policy.class%
        parent: ezrepoforms.action_dispatcher.base

    # Form processors
    ezrepoforms.form_processor.role:
        class: %ezrepoforms.form_processor.role.class%
        arguments: [@ezpublish.api.service.role]
        tags:
            - { name: kernel.event_subscriber }

    ezrepoforms.form_processor.policy:
        class: %ezrepoforms.form_processor.policy.class%
        arguments: [@ezpublish.api.service.role]
        tags:
            - { name: kernel.event_subscriber }

    ezrepoforms.limitation_form_mapper.registry:
        class: %ezrepoforms.limitation_form_mapper.registry.class%

    ezrepoforms.limitation.form_mapper.siteaccess:
        class: %ezrepoforms.limitation.form_mapper.siteaccess.class%
        arguments: [%ezpublish.siteaccess.list%]
        tags:
            - { name: ez.limitation.formMapper, limitationType: SiteAccess }
