contenttype/create:
    path: /contenttype/create/{contentTypeGroupId}/{languageCode}
    defaults: { _controller: EzSystemsRepositoryFormsBundle:ContentType:createContentType, languageCode: ~ }

contenttype/update:
    path: /contenttype/update/{contentTypeId}/{languageCode}
    defaults: { _controller: EzSystemsRepositoryFormsBundle:ContentType:updateContentType, languageCode: ~ }
