parameters:
    ezrepoforms.field_type_form_mapper.registry.class: EzSystems\RepositoryForms\FieldType\FieldTypeFormMapperRegistry
    ezrepoforms.content_type.update.form_type.class: EzSystems\RepositoryForms\Form\Type\ContentTypeUpdateType
    ezrepoforms.field_definition.form_type.class: EzSystems\RepositoryForms\Form\Type\FieldDefinition\FieldDefinitionType

    ezrepoforms.field_type.form_mapper.ezstring.class: EzSystems\RepositoryForms\FieldType\Mapper\TextLineFormMapper

services:
    ezrepoforms.field_type_form_mapper.registry:
        class: %ezrepoforms.field_type_form_mapper.registry.class%

    ezrepoforms.content_type.update.form_type:
        class: %ezrepoforms.content_type.update.form_type.class%
        arguments: [@ezrepoforms.field_type_form_mapper.registry]
        tags:
            - {name: form.type, alias: ezrepoforms_contenttype_update}

    ezrepoforms.field_definition.form_type:
        class: %ezrepoforms.field_definition.form_type.class%
        arguments: [@ezrepoforms.field_type_form_mapper.registry, @ezpublish.api.service.field_type]
        tags:
            - { name: form.type, alias: ezrepoforms_fielddefinition_update }

    # FieldType form mappers
    ezrepoforms.field_type.form_mapper.ezstring:
        class: %ezrepoforms.field_type.form_mapper.ezstring.class%
        tags:
            - { name: ez.fieldType.formMapper, fieldType: ezstring }
